### ISSUE TITLE
Create authentication express routes

### ISSUE THREAD

**Issue by bramz** [bramz/maat#1]
Build express authentication routes

`/login` - user login
`/register` - user registration
`/dashboard` - user dashboard

**Comment by fuadop** [comment]
Hey @bramz , Looks like you implemented a /register route already ?

**Comment by fuadop** [comment]
Also what do you mean by a /dashboard route ?

**Comment by fuadop** [comment]
what type of authentication do you plan on using for /login ? jwt in Bearer header ?

**Comment by bramz** [comment]
> what type of authentication do you plan on using for /login ? jwt in Bearer header ?

Yes I'm planning on using jwt in header, the `/dashboard` route will likely turn into the `/` route once authentication is finished. I was just stubbing out the idea and have been using `/dashboard` until auth is working. 

I have started working on this a bit, but have commented out some of the code while I worked on some design tweaks.

**Comment by bramz** [comment]
@fuadop all PRs are welcome, and all contributions are greatly appreciated. Any implementations or ideas you wish to bring to this project, please feel free to do so. As you have probably noticed this app is a new idea I had and a WIP. Feel free to bring on any knowledge you may have that I do not, look forward to the reviews. 👍

**Comment by bramz** [comment]
Resolved.
