### ISSUE TITLE
Dockerize 

### ISSUE THREAD

**Issue by bramz** [bramz/maat#6]
Build docker images, containers, files to orchestrate deployments.
[https://docs.docker.com/compose/](https://docs.docker.com/compose/)

**Comment by Damola12345** [comment]
hi @bramz can i work on this file ?

**Comment by bramz** [comment]
@Damola12345 sure! All PRs welcome! Appreciate it!

**Comment by Damola12345** [comment]
@bramz nice 
will work on it

**Comment by bramz** [comment]
Thanks!

**Comment by bramz** [comment]
@Damola12345 if you have any questions about the local setup I'm always available to chat. Feel free to email me brockramz@gmail.com Thanks again for the contribution!

**Comment by Damola12345** [comment]
Okay bro will send you a mail 

I have issues with the app

**Comment by Damola12345** [comment]
im getting this error from the "app folder" 
" models/sequelize/index.model.ts(1,20): error TS2307: Cannot find module '../../data/db.config' or its corresponding type declarations."
